
package org.ccci.soa.pshr.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StaffServiceService", targetNamespace = "http://service.staff.ccci.org/", wsdlLocation = "http://localhost:8080/pshr/pshr?wsdl")
public class StaffServiceService
    extends Service
{

    private final static URL STAFFSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ccci.soa.pshr.client.StaffServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ccci.soa.pshr.client.StaffServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/pshr/pshr?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/pshr/pshr?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STAFFSERVICESERVICE_WSDL_LOCATION = url;
    }

    public StaffServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffServiceService() {
        super(STAFFSERVICESERVICE_WSDL_LOCATION, new QName("http://service.staff.ccci.org/", "StaffServiceService"));
    }

    /**
     * 
     * @return
     *     returns StaffService
     */
    @WebEndpoint(name = "StaffServicePort")
    public StaffService getStaffServicePort() {
        return super.getPort(new QName("http://service.staff.ccci.org/", "StaffServicePort"), StaffService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StaffService
     */
    @WebEndpoint(name = "StaffServicePort")
    public StaffService getStaffServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.staff.ccci.org/", "StaffServicePort"), StaffService.class, features);
    }

}
