
package org.ccci.soa.pshr.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StaffService", targetNamespace = "http://service.staff.ccci.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffService {


    /**
     * 
     * @param serverSecret
     * @param serverId
     * @param emplid
     * @return
     *     returns org.ccci.soa.pshr.client.UsStaffMember
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaff", targetNamespace = "http://service.staff.ccci.org/", className = "org.ccci.soa.pshr.client.GetStaff")
    @ResponseWrapper(localName = "getStaffResponse", targetNamespace = "http://service.staff.ccci.org/", className = "org.ccci.soa.pshr.client.GetStaffResponse")
    public UsStaffMember getStaff(
        @WebParam(name = "serverId", targetNamespace = "http://service.staff.ccci.org/")
        String serverId,
        @WebParam(name = "serverSecret", targetNamespace = "http://service.staff.ccci.org/")
        String serverSecret,
        @WebParam(name = "emplid", targetNamespace = "http://service.staff.ccci.org/")
        String emplid)
        throws Exception_Exception
    ;

}
